name: Build

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image for Node.js
        if: ${{ inputs.language == 'nodejs' }}
        run: |
          docker build -t $IMAGE_REPO_NAME:latest .

      - name: Build Docker Image for Java
        if: ${{ inputs.language == 'java' }}
        run: |
          docker build -t $IMAGE_REPO_NAME:latest .

      - name: Tag Docker Image
        run: |
          IMAGE_TAG=${{ github.sha::0:7 }}
          docker tag $IMAGE_REPO_NAME:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.ECR_REGION }}.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
