name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ECR_REGION: us-east-1  # Replace with your AWS region
  IMAGE_REPO_NAME: my-app  # Replace with your ECR repository name

permissions:
  contents: read
  id-token: write
  packages: write
  actions: write

jobs:
  # 1. Generate Pipeline (Optional: Dynamic steps for scaffolding/config)
  generate-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Generate workflow files
        run: |
          python scripts/init.py  # Replace with your script


  # Push Docker Image to ECR
  push-to-ecr:
    runs-on: ubuntu-latest
    needs: [nodejs, java]
    steps:
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.ECR_REGION }}.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
