name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ECR_REGION: us-east-1  # Replace with your AWS region
  IMAGE_REPO_NAME: my-app  # Replace with your ECR repository name

permissions:
  contents: read
  id-token: write
  packages: write
  actions: write

jobs:
  detect-language:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Detect language
        run: |
          if [ -f "package.json" ]; then
            echo "nodejs"
          elif [ -f "pom.xml" ]; then
            echo "java"
          else
            echo "unknown"
          fi
      - name: Set Language Output
        id: language
        run: echo "::set-output name=language::$(cat <<<'${{ steps.detect-language.outputs }}')"
