name: CI/CD Pipeline

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      backend_dynamodb_table:
        description: DynamoDB table for State lock
        default: "terraform-backend-ddb"
        type: string
      backend_s3_bucket:
        description: Name of the S3bucket for Terraform backend
        default: "terraform-backend-primary-ec2"
        type: string
      environment:
        description: Environment
        default: "dev"
        type: string

env:
  AWS_REGION: us-east-1
  IMAGE_REPO_NAME: my-java-app
  AWS_ACCOUNT_ID: 992382383822
  IAM_ROLE: github-actions-runner

permissions:
  contents: read
  id-token: write
  packages: write
  actions: write

jobs:
  prepare:  
    name: prepare # More descriptive name for preparing the combined repository
    uses: ./.github/workflows/prepare.yml

  analyze:  # More descriptive name for analyzing the merged repository
    name: analyze
    uses: ./.github/workflows/analyze.yml
    needs: prepare
    
  test:
    name: test
    uses: ./.github/workflows/test.yml
    needs: analyze
    with:
      language: ${{ inputs.language }}
