name: CI/CD Pipeline

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      backend_dynamodb_table:
        description: DynamoDB table for State lock
        default: "terraform-backend-ddb"
        type: string
      backend_s3_bucket:
        description: Name of the S3bucket for Terraform backend
        default: "terraform-backend-primary-region"
        type: string

env:
  AWS_REGION: us-east-1
  IMAGE_REPO_NAME: my-java-app
  AWS_ACCOUNT_ID: 992382383822

permissions:
  contents: read
  id-token: write
  packages: write
  actions: write

jobs:
  terraform-provision:
    name: Terraform Provisioning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Workflow Repository
        uses: actions/checkout@v4

      - name: Debug Workflow Path
        working-directory: ${{ github.action_path }}
        run: |
          ls -la deploy_scripts
