name: CI/CD Pipeline

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      backend_dynamodb_table:
        description: DynamoDB table for State lock
        default: "terraform-backend-ddb"
        type: string
      backend_s3_bucket:
        description: Name of the S3bucket for Terraform backend
        default: "terraform-backend-primary-ec2"
        type: string
      environment:
        description: Environment
        default: "dev"
        type: string

env:
  AWS_REGION: us-east-1
  IMAGE_REPO_NAME: my-java-app
  AWS_ACCOUNT_ID: 992382383822
  IAM_ROLE: github-actions-runner

permissions:
  contents: read
  id-token: write
  packages: write
  actions: write

jobs:
  setup:
    name: Clone and Merge Repositories
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.upload.outputs.artifact-path }}

    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v4

      - name: Create Directory for Global Repository
        run: mkdir global-repository

      - name: Clone Global Repository
        run: |
          git clone https://github.com/uj-cpu-dev/deploy-to-aws-ecr.git global-repository

      - name: Copy Files from Current Repository to Global Repository
        run: |
          cp -r ./* global-repository/
          cp -r ./.github global-repository/  # Include hidden directories if needed

      - name: Upload Merged Repository as Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: global-repository
          path: global-repository

  list-contents:
    name: List Contents of Merged Repository
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Download Merged Repository Artifact
        uses: actions/download-artifact@v4
        with:
          name: global-repository
          path: global-repository

      - name: List Contents of Merged Repository
        run: ls -R global-repository