name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ECR_REGION: us-east-1  # Replace with your AWS region
  IMAGE_REPO_NAME: my-app  # Replace with your ECR repository name

permissions:
  contents: read
  id-token: write
  packages: write
  actions: write

jobs:
  generate-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Pipeline
        run: |
          if [ -f "package.json" ]; then
            echo "nodejs"
          elif [ -f "pom.xml" ]; then
            echo "java"
          else
            echo "unknown"
          fi
      - name: Set Language Output
        id: language
        run: echo "::set-output name=language::$(cat <<<'${{ steps.generate-pipeline.outputs }}')"

  nodejs:
    name: Node.js Workflow
    if: needs.generate-pipeline.outputs.language == 'nodejs'
    needs: [generate-pipeline]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint  # Replace with your linter command

      - name: Run Tests
        run: npm run test  # Replace with your test command

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_REPO_NAME:latest .

      - name: Tag Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker tag $IMAGE_REPO_NAME:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.ECR_REGION }}.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV