name: CI/CD Pipeline

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      backend_dynamodb_table:
        description: DynamoDB table for State lock
        default: "terraform-backend-ddb"
        type: string
      backend_s3_bucket:
        description: Name of the S3bucket for Terraform backend
        default: "terraform-backend-primary-ec2"
        type: string
      environment:
        description: Environment
        default: "dev"
        type: string

env:
  AWS_REGION: us-east-1
  IMAGE_REPO_NAME: my-java-app
  AWS_ACCOUNT_ID: 992382383822
  IAM_ROLE: github-actions-runner

permissions:
  contents: read
  id-token: write
  packages: write
  actions: write

jobs:
  setup:
    name: Clone Global Repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v4

      - name: Clone Another Repository Globally (Adjusted Path)
        run: |
          git clone https://github.com/uj-cpu-dev/deploy-to-aws-ecr.git global-repository  # Clone directly into a folder

      - name: Upload Cloned Repository as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: global-repository  # Same name as the folder
          path: global-repository  # Upload the folder itself

  list-repositories:
    name: List Repositories Content
    runs-on: ubuntu-latest
    needs: setup  # Wait for the setup job to finish

    steps:
      - name: Download Global Repository Artifact
        uses: actions/checkout@v4
    
      - name: Check Repository
        run: ls -la

      - name: Download Global Repository Artifact
        uses: actions/download-artifact@v4
        with:
          name: global-repository
          path: ./global-repository  # Download to the current directory

      - name: List Contents of the Current Repository
        run: |
          echo "Listing contents of the current repository:"
          ls -R .  # Lists the content of the current repository

      - name: List Contents of the Global Repository
        run: |
          echo "Listing contents of the global repository:"
          ls -R ./global-repository  # Lists the content of the downloaded global repository
