name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ECR_REGION: us-east-1
  IMAGE_REPO_NAME: my-app

permissions:
  contents: read
  id-token: write
  packages: write
  actions: write

jobs:
  # 1. Generate Pipeline
  generate-pipeline:
    uses: ./.github/workflows/generate-pipeline.yml

  # 2. Run Tests
  run-tests:
    needs: generate-pipeline
    uses: ./.github/workflows/run-tests.yml
    with:
      language: ${{ needs.generate-pipeline.outputs.language }}

  # 3. Build
  build:
    needs: run-tests
    uses: ./.github/workflows/build.yml
    with:
      language: ${{ needs.run-tests.inputs.language }}

  # 4. Push to ECR
  push-to-ecr:
    needs: build
    uses: ./.github/workflows/push-to-ecr.yml
    with:
      image_tag: ${{ env.IMAGE_TAG }}
