name: CI/CD Pipeline

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      backend_dynamodb_table:
        description: DynamoDB table for State lock
        default: "terraform-backend-ddb"
        type: string
      backend_s3_bucket:
        description: Name of the S3bucket for Terraform backend
        default: "terraform-backend-primary-ec2"
        type: string
      environment:
        description: Environment
        default: "dev"
        type: string

env:
  AWS_REGION: us-east-1
  IMAGE_REPO_NAME: my-java-app
  AWS_ACCOUNT_ID: 992382383822
  IAM_ROLE: github-actions-runner

permissions:
  contents: read
  id-token: write
  packages: write
  actions: write

jobs:
  bundle-repository:
    name: Bundle Repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v4

      - name: Checkout Second Repository
        uses: actions/checkout@v4
        with:
          repository: uj-cpu-dev/deploy-to-aws-ecr
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Bundle Folder
        run: |
          mkdir combined-repository
          cp -r ./* combined-repository/
          cp -r /path/to/second/repository/* combined-repository/

      - name: Upload Combined Repository as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: repository-bundle
          path: ./combined-repository

  generate-pipeline:
    name: Generate Pipeline
    runs-on: ubuntu-latest
    needs: bundle-repository
    outputs:
      language: ${{ steps.detect.outputs.language }}
      java_version: ${{ steps.detect.outputs.java_version }}
      node_version: ${{ steps.detect.outputs.node_version }}
    steps:
      - name: Download Bundle
        uses: actions/download-artifact@v4
        with:
          name: repository-bundle
      
      - name: Use Files from Bundle
        run: |
          echo "Listing the contents of the bundled repository:"
          ls -R ./repository-bundle/