name: Push to ECR

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string

jobs:
  push-image:
    name: Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.ECR_REGION }}.amazonaws.com/$IMAGE_REPO_NAME:${{ inputs.image_tag }}
