name: Test Template

on:
 workflow_call:
  inputs:
    language: 
      required: true
      type: string

jobs:
  app:
    name: test
    runs-on: ubuntu-latest
    
    steps:
     - name: Run Linguist
       id: linguist
       uses: lowlighter/metrics@latest
       with:
          plugin_languages: true

     - name: Output Detected Languages
       run: |
          echo "Detected languages: ${{ steps.linguist.outputs.languages }}"

     - name: Set up Python
       uses: actions/setup-python@v4
       with:
        python-version: '3.9'

     - name: Check Java Version
       if: ${{ steps.linguist.outputs.languages == 'java' }}
       id: java_info
       uses: YunaBraska/java-info-action@main

     - name: Set up Java
       uses: actions/setup-java@v4
       if: ${{ steps.linguist.outputs.languages == 'java' }}
       with:
         distribution: 'temurin'
         java-version: ${{ steps.java_info.outputs.java_version }}

     - name: Run Tests Based on Detected Language
       run: |
         python global-repository/scripts/run_tests.py ${{ steps.linguist.outputs.languages }}

